### ISSUE TITLE
Hello, I'm getting this error

### ISSUE THREAD

**Issue by odorizzioficial** [RaoHammas/Social-Space#1]
Hello, I found your application very interesting, but when I open it in Windows 10, this error appears, and I installed Net.Core 7 and even so the error appears, could you help me? And another thing, I have a channel on YouTube can I present your application to my audience?

**Comment by odorizzioficial** [comment]
![2023-07-01_14-16](https://github.com/RaoHammas/Social-Space/assets/110546717/29361ea3-e1c4-48eb-a7d2-827816b1911d)

**Comment by RaoHammas** [comment]
Hi,
Thank you for reaching out here (I missed the notification, otherwise I would have replied to you very early).  I'm gonna look into it right now and will get back to you.

Thank you.

**Comment by RaoHammas** [comment]
@odorizzioficial  Hello, I've released a totally new version. You can check that out, I hope you'll like it.

**Comment by RaoHammas** [comment]
@odorizzioficial hey, did you make a video?
